version = 1

exclude_patterns = ["discord", "discord/*", "discord/ext", "discord/ext/*", "discord/ext/commands", "discord/ext/commands/*", "discord/bin/*", "discord/types/*", "discord/webhook/*"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"
enabled = true
